---

category_names_file: ./dataset/class.names
output_dir: ./runs/exp

# output types selection:
label_file_formats:
  coco_detection_datase:
    annotations_path: ./dataset/train/images/annotations.json
  yolov5_detection_format:
      image_dir: ./dataset/train/images
      label_dir: ./dataset/train/labels
  single_label_file_format:
      label_path: ./dataset/train/all_entries.txt

  yolov5_segmentation_format:
    image_dir: ./dataset/train/images
    label_dir: ./dataset/train/labels-seg


