---
image_size:
 - 416
 - 416

min_objects_in_image: 3
max_objects_in_image: 3
x_diameter_choices:
 - 60
bg_color:
  - 0
  - 0
  - 0
  
margin_from_edge: 8
bbox_margin: 5
size_fluctuation: 0.00
iou_thresh: 0
num_of_examples: 1000
images_dir:  dataset/images/
annotations_path:  dataset/annotations/annotations.json
class_names_file:  dataset/class.names                      # class_mode values: ['shape' 'color', 'color_and_shape'

