---
image_size:
 - 416
 - 416

min_objects_in_image: 1
max_objects_in_image: 1
x_diameter_choices:
 - 60
bg_color:
  - 0
  - 0
  - 0
  
margin_from_edge: 8
bbox_margin: 5
size_fluctuation: 0.00
iou_thresh: 0
splits:
 train: 700
 valid: 200
 test: 100

output_dir: dataset

class_names_file:  class.names

