---

image_size:
 - 640
 - 640

min_objects_in_image: 3
max_objects_in_image: 3

bg_color:
  - 0
  - 0
  - 0

# min margin between objects and image edged in pixels:
margin_from_edge: 8
# margin betweem bbox and shape - in pixels:
bbox_margin: 5
# fluctuations of object size:
size_fluctuation: 0.00
# max permited objects overlap. iou=0 means no overlap
iou_thresh: 0
# Notes:
# supported shapes: circle, triangle, ellipse, square, trapezoid, rectangle, hexagon
# color field is used for class labeling in 'color' or 'color' and 'shape' mode.

class_names_file:  class.names

shapes:
- id: 0
  color: red
  category_name: circle
  super_category: shapes
  fill_color:
    - 255
    - 0
    - 0
  outline_color:
    - 255
    - 0
    - 0
  shape_aspect_ratio: 1
  shape_width_choices:
    - 240
    - 120
    - 60

- id: 1

  color: red
  category_name: ellipse
  super_category: shapes
  fill_color:
    - 255
    - 0
    - 0
  outline_color:
    - 255
    - 0
    - 0
  shape_aspect_ratio: 2
  shape_width_choices:
    - 240
    - 120
    - 60

#- shape: circle
#  color: blue
#  category_name: circle
#  super_category: shapes
#  fill_color:
#    - 0
#    - 0
#    - 255
#  outline_color:
#    - 0
#    - 0
#    - 255
#  shape_aspect_ratio: 1
#  shape_width_choices:
#    - 60
#
#- shape: triangle
#  color: blue
#  category_name: triangle
#  super_category: shapes
#  fill_color:
#    - 0
#    - 0
#    - 255
#  outline_color:
#    - 0
#    - 0
#    - 255
#  shape_aspect_ratio: 1
#  shape_width_choices:
#    - 60
#
#- shape: triangle
#  color: green
#  category_name: triangle
#  super_category: shapes
#  fill_color:
#    - 0
#    - 255
#    - 0
#  outline_color:
#    - 0
#    - 255
#    - 0
#  shape_aspect_ratio: 1
#  shape_width_choices:
#   - 60
#
#- shape: circle
#  color: red
#  category_name: circle
#  super_category: shapes
#  fill_color:
#    - 255
#    - 0
#    - 0
#  outline_color:
#    - 255
#    - 0
#    - 0
#  shape_aspect_ratio: 1
#  shape_width_choices:
#    - 30
#
#- shape: circle
#  color: blue
#  category_name: circle
#  super_category: shapes
#  fill_color:
#    - 0
#    - 0
#    - 255
#  outline_color:
#    - 0
#    - 0
#    - 255
#  shape_aspect_ratio: 1
#  shape_width_choices:
#    - 30
#
#
#
